name = "GEBT"
uuid = "974624c9-1acb-4ad6-a627-8ac40fc27a3e"
authors = ["Taylor McDonnell <taylor.golden.mcdonnell@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
